plugins {
    id 'java'
}

group = 'ir.kootletland'
version = '1.0.0'

java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }


dependencies { compileOnly 'io.papermc.paper:paper-api:1.21.8-R0.1-SNAPSHOT'; testImplementation 'org.junit.jupiter:junit-jupiter-api:5.12.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.12.2' }

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8'; options.release = 21 }
tasks.test { useJUnitPlatform() }

processResources { filesMatching('plugin.yml') { expand(version: project.version) } }
